import Request from "./lib/https";
import { iInAppToken, iRequestSenderId, iSendBulkMessage, iSendMessage, iSendToken, iSendWithAutoGeneratedNumber } from "./types";

export default class Termii {
    private apiKey: string;
    private baseUrl: string = 'https://api.ng.termii.com';

    private senderId: string;
    private maxAttempts: number = 3;
    private pinTimeToLive: number = 0;
    private pinLength: number = 6;
    private pinPlaceholder: string = "< _pin_ >";
    private pinType: string = "NUMERIC";
    private channel: string = "generic";
    private tokenMessageType: string = "ALPHANUMERIC";
    private messageType: string = "plain";

    constructor(apiKey: string, senderId: string) {
        this.apiKey = apiKey
        this.senderId = senderId
    }


    /**
     * This API allows businesses retrieve the status of all registered sender ID.
     * @returns Returns json data.
     */
    fetchSenderId = async () => {
        return await new Request(this.baseUrl)
            .get(`api/sender-id?api_key=${this.apiKey}`)
    }

    /**
     * The Balance API returns your total balance and balance 
     * information from your wallet, such as currency.
     * @returns Returns json data.
     */
    fetchBalance = async () => {
        return await new Request(this.baseUrl)
            .get(`api/get-balance?api_key=${this.apiKey}`)
    }

    /**
     * The search API allows businesses verify phone numbers and 
     * automatically detect their status as well as current network.
     * @param phoneNumber 
     * @returns Returns json data.
     */
    search = async (phoneNumber: string) => {
        return await new Request(this.baseUrl)
            .get(`api/check/dnd?api_key=${this.apiKey}&phone_number=${phoneNumber}`)
    }

    /**
     * This Inbox API returns reports for messages sent across the sms, voice & whatsapp channels.
     * @returns Returns json data.
     */
    history = async () => {
        return await new Request(this.baseUrl)
            .get(`api/sms/inbox?api_key=${this.apiKey}`)
    }

    /**
     * This API allows businesses request registration of sender ID on Termii.
     * @param data 
         * @returns Returns json data.
     */
    requestSenderId = async (data: iRequestSenderId) => {
        data.sender_id = data.sender_id || this.senderId;
        return await new Request(this.baseUrl)
            .post(`api/sender-id/request`, data)
    }

    /**
     * This API allows businesses send text messages to their customers 
     * across different messaging channels
     * @param data 
     * @returns Returns json data.
     */
    sendMessage = async (data: iSendMessage) => {
        data.from = data.from || this.senderId;
        data.api_key = data.api_key || this.apiKey;
        data.channel = data.channel || this.channel;
        data.type = data.type || this.messageType;
        return await new Request(this.baseUrl)
            .post(`api/sms/send`, data)
    }

    /**
     * This API allows businesses send text messages to multiple customers 
     * at once, across different messaging channels
     * @param data 
     * @returns Returns json data.
     */
    sendBulkMessage = async (data: iSendBulkMessage) => {
        data.from = data.from || this.senderId;
        data.api_key = data.api_key || this.apiKey;
        data.channel = data.channel || this.channel;
        data.type = data.type || this.messageType;
        return await new Request(this.baseUrl)
            .post(`api/sms/send`, data)
    }

    /**
     * This API allows businesses send messages to customers using Termii's 
     * auto-generated messaging numbers that adapt to customers location.
     * @param data 
     * @returns Returns json data.
     */
    sendWithAutoGeneratedNumber = async (data: iSendWithAutoGeneratedNumber) => {
        data.api_key = data.api_key || this.apiKey;
        return await new Request(this.baseUrl)
            .post(`api/sms/number/send`, data)
    }

    /**
     * The send token API allows businesses trigger one-time-passwords (OTP) 
     * across any available messaging channel on Termii.
     * @param data 
     * @returns Returns json data.
     */
    sendToken = async (data: iSendToken) => {
        data.from = data.from || this.senderId;
        data.api_key = data.api_key || this.apiKey;
        data.message_type = data.message_type || this.tokenMessageType;
        data.channel = data.channel || this.channel;
        data.pin_attempts = data.pin_attempts || this.maxAttempts;
        data.pin_time_to_live = data.pin_time_to_live || this.pinTimeToLive;
        data.pin_length = data.pin_length || this.pinLength;
        data.pin_placeholder = data.pin_placeholder || this.pinPlaceholder;
        return await new Request(this.baseUrl)
            .post(`api/sms/otp/send`, data)
    }

    /**
     * This API returns OTP codes in JSON format which can be used within any web or mobile app.
     * @param data 
     * @returns Returns json data.
     */
    inAppToken = async (data: iInAppToken) => {
        data.api_key = data.api_key || this.apiKey;
        data.pin_type = data.pin_type || this.pinType;
        data.pin_attempts = data.pin_attempts || this.maxAttempts;
        data.pin_time_to_live = data.pin_time_to_live || this.pinTimeToLive;
        data.pin_length = data.pin_length || this.pinLength;
        return await new Request(this.baseUrl)
            .post(`api/sms/otp/generate`, data)
    }


}
